version: '2'
services:
    haoyaoge-app:
        image: haoyaoge
        external_links:
            - haoyaoge-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=haoyaoge
        ports:
            - 8080:8080
    haoyaoge-mongodb:
        extends:
            file: mongodb.yml
            service: haoyaoge-mongodb
