version: '2'
services:
    haoyaoge-app:
        image: haoyaoge
        external_links:
            - haoyaoge-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/haoyaoge?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    haoyaoge-mysql:
        extends:
            file: mysql.yml
            service: haoyaoge-mysql
