version: '2'
services:
    haoyaoge-mongodb:
        container_name: haoyaoge-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        command: mongos --configdb haoyaoge-mongodb-config
    haoyaoge-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    haoyaoge-mongodb-config:
        image: mongo:3.2.3
        container_name: haoyaoge-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
